#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 19
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_POUND = 1,
  anon_sym_STAR = 2,
  anon_sym_DASH = 3,
  anon_sym_DOLLAR = 4,
  anon_sym_TILDE = 5,
  anon_sym_COMMA = 6,
  anon_sym_DOT = 7,
  anon_sym_PERCENT = 8,
  anon_sym_PLUS = 9,
  anon_sym_SEMI = 10,
  anon_sym_BQUOTE = 11,
  anon_sym_BANG = 12,
  anon_sym_AT = 13,
  anon_sym_CARET = 14,
  anon_sym_AMP = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  anon_sym_LBRACE = 18,
  anon_sym_RBRACE = 19,
  anon_sym_LBRACK = 20,
  anon_sym_RBRACK = 21,
  anon_sym_BSLASH = 22,
  anon_sym_PIPE = 23,
  anon_sym_SLASH = 24,
  anon_sym_QMARK = 25,
  anon_sym_SQUOTE = 26,
  anon_sym_EQ = 27,
  anon_sym_DQUOTE = 28,
  anon_sym_LF = 29,
  anon_sym_TAB = 30,
  anon_sym_TAB_TAB = 31,
  anon_sym_TAB_TAB_TAB = 32,
  aux_sym_identifier_token1 = 33,
  anon_sym_ = 34,
  sym_bold_symbol_s = 35,
  sym_bold_symbol_e = 36,
  sym_underline_symbol = 37,
  sym_source_file = 38,
  sym__definition = 39,
  sym_starter = 40,
  sym_symbol = 41,
  sym_title_starter = 42,
  sym_header_starter = 43,
  sym_subheader_starter = 44,
  sym_section_starter = 45,
  sym_title_definition = 46,
  sym_header_definition = 47,
  sym_subheader_definition = 48,
  sym_section_definition = 49,
  sym_normal_definition = 50,
  sym_text = 51,
  sym_expression = 52,
  sym_identifier = 53,
  sym_bold_identifier = 54,
  sym_bold_text = 55,
  sym_underlined_identifier = 56,
  sym_underlined_text = 57,
  aux_sym_source_file_repeat1 = 58,
  aux_sym_title_definition_repeat1 = 59,
  aux_sym_section_definition_repeat1 = 60,
  aux_sym_bold_text_repeat1 = 61,
  aux_sym_underlined_text_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [anon_sym_STAR] = "*",
  [anon_sym_DASH] = "-",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_TILDE] = "~",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS] = "+",
  [anon_sym_SEMI] = ";",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_BANG] = "!",
  [anon_sym_AT] = "@",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_PIPE] = "|",
  [anon_sym_SLASH] = "/",
  [anon_sym_QMARK] = "\?",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_EQ] = "=",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_LF] = "\n",
  [anon_sym_TAB] = "\t",
  [anon_sym_TAB_TAB] = "\t\t",
  [anon_sym_TAB_TAB_TAB] = "\t\t\t",
  [aux_sym_identifier_token1] = "identifier_token1",
  [anon_sym_] = " ",
  [sym_bold_symbol_s] = "bold_symbol_s",
  [sym_bold_symbol_e] = "bold_symbol_e",
  [sym_underline_symbol] = "underline_symbol",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_starter] = "starter",
  [sym_symbol] = "symbol",
  [sym_title_starter] = "title_starter",
  [sym_header_starter] = "header_starter",
  [sym_subheader_starter] = "subheader_starter",
  [sym_section_starter] = "section_starter",
  [sym_title_definition] = "title_definition",
  [sym_header_definition] = "header_definition",
  [sym_subheader_definition] = "subheader_definition",
  [sym_section_definition] = "section_definition",
  [sym_normal_definition] = "normal_definition",
  [sym_text] = "text",
  [sym_expression] = "expression",
  [sym_identifier] = "identifier",
  [sym_bold_identifier] = "bold_identifier",
  [sym_bold_text] = "bold_text",
  [sym_underlined_identifier] = "underlined_identifier",
  [sym_underlined_text] = "underlined_text",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_title_definition_repeat1] = "title_definition_repeat1",
  [aux_sym_section_definition_repeat1] = "section_definition_repeat1",
  [aux_sym_bold_text_repeat1] = "bold_text_repeat1",
  [aux_sym_underlined_text_repeat1] = "underlined_text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_TAB] = anon_sym_TAB,
  [anon_sym_TAB_TAB] = anon_sym_TAB_TAB,
  [anon_sym_TAB_TAB_TAB] = anon_sym_TAB_TAB_TAB,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [anon_sym_] = anon_sym_,
  [sym_bold_symbol_s] = sym_bold_symbol_s,
  [sym_bold_symbol_e] = sym_bold_symbol_e,
  [sym_underline_symbol] = sym_underline_symbol,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_starter] = sym_starter,
  [sym_symbol] = sym_symbol,
  [sym_title_starter] = sym_title_starter,
  [sym_header_starter] = sym_header_starter,
  [sym_subheader_starter] = sym_subheader_starter,
  [sym_section_starter] = sym_section_starter,
  [sym_title_definition] = sym_title_definition,
  [sym_header_definition] = sym_header_definition,
  [sym_subheader_definition] = sym_subheader_definition,
  [sym_section_definition] = sym_section_definition,
  [sym_normal_definition] = sym_normal_definition,
  [sym_text] = sym_text,
  [sym_expression] = sym_expression,
  [sym_identifier] = sym_identifier,
  [sym_bold_identifier] = sym_bold_identifier,
  [sym_bold_text] = sym_bold_text,
  [sym_underlined_identifier] = sym_underlined_identifier,
  [sym_underlined_text] = sym_underlined_text,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_title_definition_repeat1] = aux_sym_title_definition_repeat1,
  [aux_sym_section_definition_repeat1] = aux_sym_section_definition_repeat1,
  [aux_sym_bold_text_repeat1] = aux_sym_bold_text_repeat1,
  [aux_sym_underlined_text_repeat1] = aux_sym_underlined_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB_TAB_TAB] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [sym_bold_symbol_s] = {
    .visible = true,
    .named = true,
  },
  [sym_bold_symbol_e] = {
    .visible = true,
    .named = true,
  },
  [sym_underline_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_starter] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_title_starter] = {
    .visible = true,
    .named = true,
  },
  [sym_header_starter] = {
    .visible = true,
    .named = true,
  },
  [sym_subheader_starter] = {
    .visible = true,
    .named = true,
  },
  [sym_section_starter] = {
    .visible = true,
    .named = true,
  },
  [sym_title_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_header_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_subheader_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_section_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_normal_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_bold_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_bold_text] = {
    .visible = true,
    .named = true,
  },
  [sym_underlined_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_underlined_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_title_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bold_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_underlined_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 8,
  [18] = 9,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\t') ADVANCE(33);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == ' ') ADVANCE(37);
      if (lookahead == '!') ADVANCE(14);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == '%') ADVANCE(10);
      if (lookahead == '&') ADVANCE(17);
      if (lookahead == '\'') ADVANCE(28);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '+') ADVANCE(11);
      if (lookahead == ',') ADVANCE(8);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '<') ADVANCE(38);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '?') ADVANCE(27);
      if (lookahead == '@') ADVANCE(15);
      if (lookahead == '[') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead == ']') ADVANCE(23);
      if (lookahead == '^') ADVANCE(16);
      if (lookahead == '`') ADVANCE(13);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '|') ADVANCE(25);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '~') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(32);
      if (lookahead == ' ') ADVANCE(37);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == '%') ADVANCE(10);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '+') ADVANCE(11);
      if (lookahead == ',') ADVANCE(8);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '~') ADVANCE(7);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_TAB);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead == '\t') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_TAB_TAB);
      if (lookahead == '\t') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_TAB_TAB_TAB);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_bold_symbol_s);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_bold_symbol_e);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_underline_symbol);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_TAB] = ACTIONS(1),
    [anon_sym_TAB_TAB] = ACTIONS(1),
    [anon_sym_TAB_TAB_TAB] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [anon_sym_] = ACTIONS(3),
    [sym_bold_symbol_s] = ACTIONS(1),
    [sym_bold_symbol_e] = ACTIONS(1),
    [sym_underline_symbol] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(57),
    [sym__definition] = STATE(41),
    [sym_starter] = STATE(45),
    [sym_title_starter] = STATE(39),
    [sym_title_definition] = STATE(41),
    [sym_header_definition] = STATE(41),
    [sym_subheader_definition] = STATE(41),
    [sym_section_definition] = STATE(41),
    [sym_normal_definition] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(7),
    [anon_sym_TILDE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_LF] = ACTIONS(9),
    [anon_sym_TAB] = ACTIONS(11),
    [anon_sym_TAB_TAB] = ACTIONS(13),
    [anon_sym_TAB_TAB_TAB] = ACTIONS(15),
    [anon_sym_] = ACTIONS(3),
  },
  [2] = {
    [sym_symbol] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_POUND] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_DOLLAR] = ACTIONS(19),
    [anon_sym_TILDE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_PERCENT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_SEMI] = ACTIONS(19),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_AT] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(19),
    [anon_sym_AMP] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_RBRACK] = ACTIONS(19),
    [anon_sym_BSLASH] = ACTIONS(19),
    [anon_sym_PIPE] = ACTIONS(19),
    [anon_sym_SLASH] = ACTIONS(19),
    [anon_sym_QMARK] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_EQ] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_TAB] = ACTIONS(21),
    [anon_sym_TAB_TAB] = ACTIONS(21),
    [anon_sym_TAB_TAB_TAB] = ACTIONS(17),
    [aux_sym_identifier_token1] = ACTIONS(17),
    [anon_sym_] = ACTIONS(3),
    [sym_bold_symbol_s] = ACTIONS(17),
    [sym_underline_symbol] = ACTIONS(17),
  },
  [3] = {
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [anon_sym_TILDE] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_SEMI] = ACTIONS(23),
    [anon_sym_BQUOTE] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(23),
    [anon_sym_AT] = ACTIONS(23),
    [anon_sym_CARET] = ACTIONS(23),
    [anon_sym_AMP] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_BSLASH] = ACTIONS(23),
    [anon_sym_PIPE] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_QMARK] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(23),
    [anon_sym_TAB] = ACTIONS(25),
    [anon_sym_TAB_TAB] = ACTIONS(25),
    [anon_sym_TAB_TAB_TAB] = ACTIONS(23),
    [aux_sym_identifier_token1] = ACTIONS(23),
    [anon_sym_] = ACTIONS(3),
    [sym_bold_symbol_s] = ACTIONS(23),
    [sym_underline_symbol] = ACTIONS(23),
  },
  [4] = {
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_PIPE] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_SQUOTE] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_TAB] = ACTIONS(29),
    [anon_sym_TAB_TAB] = ACTIONS(29),
    [anon_sym_TAB_TAB_TAB] = ACTIONS(27),
    [aux_sym_identifier_token1] = ACTIONS(27),
    [anon_sym_] = ACTIONS(3),
    [sym_bold_symbol_s] = ACTIONS(27),
    [sym_underline_symbol] = ACTIONS(27),
  },
  [5] = {
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_DOLLAR] = ACTIONS(31),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(31),
    [anon_sym_DOT] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_SEMI] = ACTIONS(31),
    [anon_sym_BQUOTE] = ACTIONS(31),
    [anon_sym_BANG] = ACTIONS(31),
    [anon_sym_AT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(31),
    [anon_sym_AMP] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(31),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(31),
    [anon_sym_BSLASH] = ACTIONS(31),
    [anon_sym_PIPE] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(31),
    [anon_sym_EQ] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LF] = ACTIONS(31),
    [anon_sym_TAB] = ACTIONS(33),
    [anon_sym_TAB_TAB] = ACTIONS(33),
    [anon_sym_TAB_TAB_TAB] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(31),
    [anon_sym_] = ACTIONS(3),
    [sym_bold_symbol_s] = ACTIONS(31),
    [sym_underline_symbol] = ACTIONS(31),
  },
  [6] = {
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_DOLLAR] = ACTIONS(35),
    [anon_sym_TILDE] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(35),
    [anon_sym_DOT] = ACTIONS(35),
    [anon_sym_PERCENT] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_SEMI] = ACTIONS(35),
    [anon_sym_BQUOTE] = ACTIONS(35),
    [anon_sym_BANG] = ACTIONS(35),
    [anon_sym_AT] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(35),
    [anon_sym_BSLASH] = ACTIONS(35),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_QMARK] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(35),
    [anon_sym_EQ] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_LF] = ACTIONS(35),
    [anon_sym_TAB] = ACTIONS(37),
    [anon_sym_TAB_TAB] = ACTIONS(37),
    [anon_sym_TAB_TAB_TAB] = ACTIONS(35),
    [aux_sym_identifier_token1] = ACTIONS(35),
    [anon_sym_] = ACTIONS(3),
    [sym_bold_symbol_s] = ACTIONS(35),
    [sym_underline_symbol] = ACTIONS(35),
  },
  [7] = {
    [ts_builtin_sym_end] = ACTIONS(39),
    [anon_sym_POUND] = ACTIONS(39),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(39),
    [anon_sym_DOLLAR] = ACTIONS(39),
    [anon_sym_TILDE] = ACTIONS(39),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_DOT] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(39),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_BQUOTE] = ACTIONS(39),
    [anon_sym_BANG] = ACTIONS(39),
    [anon_sym_AT] = ACTIONS(39),
    [anon_sym_CARET] = ACTIONS(39),
    [anon_sym_AMP] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_LBRACE] = ACTIONS(39),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(39),
    [anon_sym_BSLASH] = ACTIONS(39),
    [anon_sym_PIPE] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_QMARK] = ACTIONS(39),
    [anon_sym_SQUOTE] = ACTIONS(39),
    [anon_sym_EQ] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(39),
    [anon_sym_LF] = ACTIONS(39),
    [anon_sym_TAB] = ACTIONS(41),
    [anon_sym_TAB_TAB] = ACTIONS(41),
    [anon_sym_TAB_TAB_TAB] = ACTIONS(39),
    [aux_sym_identifier_token1] = ACTIONS(39),
    [anon_sym_] = ACTIONS(3),
    [sym_bold_symbol_s] = ACTIONS(39),
    [sym_underline_symbol] = ACTIONS(39),
  },
  [8] = {
    [ts_builtin_sym_end] = ACTIONS(43),
    [anon_sym_POUND] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_DOLLAR] = ACTIONS(43),
    [anon_sym_TILDE] = ACTIONS(43),
    [anon_sym_COMMA] = ACTIONS(43),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_PERCENT] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(43),
    [anon_sym_BANG] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(43),
    [anon_sym_CARET] = ACTIONS(43),
    [anon_sym_AMP] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(43),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(43),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_BSLASH] = ACTIONS(43),
    [anon_sym_PIPE] = ACTIONS(43),
    [anon_sym_SLASH] = ACTIONS(43),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_EQ] = ACTIONS(43),
    [anon_sym_DQUOTE] = ACTIONS(43),
    [anon_sym_LF] = ACTIONS(43),
    [anon_sym_TAB] = ACTIONS(45),
    [anon_sym_TAB_TAB] = ACTIONS(45),
    [anon_sym_TAB_TAB_TAB] = ACTIONS(43),
    [aux_sym_identifier_token1] = ACTIONS(43),
    [anon_sym_] = ACTIONS(3),
    [sym_bold_symbol_s] = ACTIONS(43),
    [sym_underline_symbol] = ACTIONS(43),
  },
  [9] = {
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_POUND] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(47),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_DOLLAR] = ACTIONS(47),
    [anon_sym_TILDE] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(47),
    [anon_sym_DOT] = ACTIONS(47),
    [anon_sym_PERCENT] = ACTIONS(47),
    [anon_sym_PLUS] = ACTIONS(47),
    [anon_sym_SEMI] = ACTIONS(47),
    [anon_sym_BQUOTE] = ACTIONS(47),
    [anon_sym_BANG] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(47),
    [anon_sym_CARET] = ACTIONS(47),
    [anon_sym_AMP] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(47),
    [anon_sym_RPAREN] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(47),
    [anon_sym_RBRACE] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(47),
    [anon_sym_RBRACK] = ACTIONS(47),
    [anon_sym_BSLASH] = ACTIONS(47),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_SLASH] = ACTIONS(47),
    [anon_sym_QMARK] = ACTIONS(47),
    [anon_sym_SQUOTE] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(47),
    [anon_sym_DQUOTE] = ACTIONS(47),
    [anon_sym_LF] = ACTIONS(47),
    [anon_sym_TAB] = ACTIONS(49),
    [anon_sym_TAB_TAB] = ACTIONS(49),
    [anon_sym_TAB_TAB_TAB] = ACTIONS(47),
    [aux_sym_identifier_token1] = ACTIONS(47),
    [anon_sym_] = ACTIONS(3),
    [sym_bold_symbol_s] = ACTIONS(47),
    [sym_underline_symbol] = ACTIONS(47),
  },
  [10] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [anon_sym_POUND] = ACTIONS(51),
    [anon_sym_STAR] = ACTIONS(51),
    [anon_sym_DASH] = ACTIONS(51),
    [anon_sym_DOLLAR] = ACTIONS(51),
    [anon_sym_TILDE] = ACTIONS(51),
    [anon_sym_COMMA] = ACTIONS(51),
    [anon_sym_DOT] = ACTIONS(51),
    [anon_sym_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS] = ACTIONS(51),
    [anon_sym_SEMI] = ACTIONS(51),
    [anon_sym_BQUOTE] = ACTIONS(51),
    [anon_sym_BANG] = ACTIONS(51),
    [anon_sym_AT] = ACTIONS(51),
    [anon_sym_CARET] = ACTIONS(51),
    [anon_sym_AMP] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_RPAREN] = ACTIONS(51),
    [anon_sym_LBRACE] = ACTIONS(51),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_LBRACK] = ACTIONS(51),
    [anon_sym_RBRACK] = ACTIONS(51),
    [anon_sym_BSLASH] = ACTIONS(51),
    [anon_sym_PIPE] = ACTIONS(51),
    [anon_sym_SLASH] = ACTIONS(51),
    [anon_sym_QMARK] = ACTIONS(51),
    [anon_sym_SQUOTE] = ACTIONS(51),
    [anon_sym_EQ] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(51),
    [anon_sym_LF] = ACTIONS(51),
    [anon_sym_TAB] = ACTIONS(53),
    [anon_sym_TAB_TAB] = ACTIONS(53),
    [anon_sym_TAB_TAB_TAB] = ACTIONS(51),
    [aux_sym_identifier_token1] = ACTIONS(51),
    [anon_sym_] = ACTIONS(3),
    [sym_bold_symbol_s] = ACTIONS(51),
    [sym_underline_symbol] = ACTIONS(51),
  },
  [11] = {
    [sym_symbol] = STATE(19),
    [sym_identifier] = STATE(19),
    [sym_underlined_identifier] = STATE(11),
    [aux_sym_underlined_text_repeat1] = STATE(11),
    [anon_sym_POUND] = ACTIONS(55),
    [anon_sym_STAR] = ACTIONS(55),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_DOLLAR] = ACTIONS(55),
    [anon_sym_TILDE] = ACTIONS(55),
    [anon_sym_COMMA] = ACTIONS(55),
    [anon_sym_DOT] = ACTIONS(55),
    [anon_sym_PERCENT] = ACTIONS(55),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_SEMI] = ACTIONS(55),
    [anon_sym_BQUOTE] = ACTIONS(55),
    [anon_sym_BANG] = ACTIONS(55),
    [anon_sym_AT] = ACTIONS(55),
    [anon_sym_CARET] = ACTIONS(55),
    [anon_sym_AMP] = ACTIONS(55),
    [anon_sym_LPAREN] = ACTIONS(55),
    [anon_sym_RPAREN] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(55),
    [anon_sym_RBRACE] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(55),
    [anon_sym_RBRACK] = ACTIONS(55),
    [anon_sym_BSLASH] = ACTIONS(55),
    [anon_sym_PIPE] = ACTIONS(55),
    [anon_sym_SLASH] = ACTIONS(55),
    [anon_sym_QMARK] = ACTIONS(55),
    [anon_sym_SQUOTE] = ACTIONS(55),
    [anon_sym_EQ] = ACTIONS(55),
    [anon_sym_DQUOTE] = ACTIONS(55),
    [aux_sym_identifier_token1] = ACTIONS(58),
    [anon_sym_] = ACTIONS(61),
    [sym_underline_symbol] = ACTIONS(64),
  },
  [12] = {
    [sym_symbol] = STATE(20),
    [sym_identifier] = STATE(20),
    [sym_bold_identifier] = STATE(12),
    [aux_sym_bold_text_repeat1] = STATE(12),
    [anon_sym_POUND] = ACTIONS(66),
    [anon_sym_STAR] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_DOLLAR] = ACTIONS(66),
    [anon_sym_TILDE] = ACTIONS(66),
    [anon_sym_COMMA] = ACTIONS(66),
    [anon_sym_DOT] = ACTIONS(66),
    [anon_sym_PERCENT] = ACTIONS(66),
    [anon_sym_PLUS] = ACTIONS(66),
    [anon_sym_SEMI] = ACTIONS(66),
    [anon_sym_BQUOTE] = ACTIONS(66),
    [anon_sym_BANG] = ACTIONS(66),
    [anon_sym_AT] = ACTIONS(66),
    [anon_sym_CARET] = ACTIONS(66),
    [anon_sym_AMP] = ACTIONS(66),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_RPAREN] = ACTIONS(66),
    [anon_sym_LBRACE] = ACTIONS(66),
    [anon_sym_RBRACE] = ACTIONS(66),
    [anon_sym_LBRACK] = ACTIONS(66),
    [anon_sym_RBRACK] = ACTIONS(66),
    [anon_sym_BSLASH] = ACTIONS(66),
    [anon_sym_PIPE] = ACTIONS(66),
    [anon_sym_SLASH] = ACTIONS(66),
    [anon_sym_QMARK] = ACTIONS(66),
    [anon_sym_SQUOTE] = ACTIONS(66),
    [anon_sym_EQ] = ACTIONS(66),
    [anon_sym_DQUOTE] = ACTIONS(66),
    [aux_sym_identifier_token1] = ACTIONS(69),
    [anon_sym_] = ACTIONS(72),
    [sym_bold_symbol_e] = ACTIONS(75),
  },
  [13] = {
    [sym_symbol] = STATE(19),
    [sym_identifier] = STATE(19),
    [sym_underlined_identifier] = STATE(11),
    [aux_sym_underlined_text_repeat1] = STATE(11),
    [anon_sym_POUND] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_DOLLAR] = ACTIONS(77),
    [anon_sym_TILDE] = ACTIONS(77),
    [anon_sym_COMMA] = ACTIONS(77),
    [anon_sym_DOT] = ACTIONS(77),
    [anon_sym_PERCENT] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(77),
    [anon_sym_SEMI] = ACTIONS(77),
    [anon_sym_BQUOTE] = ACTIONS(77),
    [anon_sym_BANG] = ACTIONS(77),
    [anon_sym_AT] = ACTIONS(77),
    [anon_sym_CARET] = ACTIONS(77),
    [anon_sym_AMP] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(77),
    [anon_sym_RBRACK] = ACTIONS(77),
    [anon_sym_BSLASH] = ACTIONS(77),
    [anon_sym_PIPE] = ACTIONS(77),
    [anon_sym_SLASH] = ACTIONS(77),
    [anon_sym_QMARK] = ACTIONS(77),
    [anon_sym_SQUOTE] = ACTIONS(77),
    [anon_sym_EQ] = ACTIONS(77),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [aux_sym_identifier_token1] = ACTIONS(79),
    [anon_sym_] = ACTIONS(81),
    [sym_underline_symbol] = ACTIONS(83),
  },
  [14] = {
    [sym_symbol] = STATE(20),
    [sym_identifier] = STATE(20),
    [sym_bold_identifier] = STATE(12),
    [aux_sym_bold_text_repeat1] = STATE(12),
    [anon_sym_POUND] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_DOLLAR] = ACTIONS(77),
    [anon_sym_TILDE] = ACTIONS(77),
    [anon_sym_COMMA] = ACTIONS(77),
    [anon_sym_DOT] = ACTIONS(77),
    [anon_sym_PERCENT] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(77),
    [anon_sym_SEMI] = ACTIONS(77),
    [anon_sym_BQUOTE] = ACTIONS(77),
    [anon_sym_BANG] = ACTIONS(77),
    [anon_sym_AT] = ACTIONS(77),
    [anon_sym_CARET] = ACTIONS(77),
    [anon_sym_AMP] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(77),
    [anon_sym_RBRACK] = ACTIONS(77),
    [anon_sym_BSLASH] = ACTIONS(77),
    [anon_sym_PIPE] = ACTIONS(77),
    [anon_sym_SLASH] = ACTIONS(77),
    [anon_sym_QMARK] = ACTIONS(77),
    [anon_sym_SQUOTE] = ACTIONS(77),
    [anon_sym_EQ] = ACTIONS(77),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [aux_sym_identifier_token1] = ACTIONS(79),
    [anon_sym_] = ACTIONS(85),
    [sym_bold_symbol_e] = ACTIONS(87),
  },
  [15] = {
    [sym_symbol] = STATE(20),
    [sym_identifier] = STATE(20),
    [sym_bold_identifier] = STATE(14),
    [aux_sym_bold_text_repeat1] = STATE(14),
    [anon_sym_POUND] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_DOLLAR] = ACTIONS(77),
    [anon_sym_TILDE] = ACTIONS(77),
    [anon_sym_COMMA] = ACTIONS(77),
    [anon_sym_DOT] = ACTIONS(77),
    [anon_sym_PERCENT] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(77),
    [anon_sym_SEMI] = ACTIONS(77),
    [anon_sym_BQUOTE] = ACTIONS(77),
    [anon_sym_BANG] = ACTIONS(77),
    [anon_sym_AT] = ACTIONS(77),
    [anon_sym_CARET] = ACTIONS(77),
    [anon_sym_AMP] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(77),
    [anon_sym_RBRACK] = ACTIONS(77),
    [anon_sym_BSLASH] = ACTIONS(77),
    [anon_sym_PIPE] = ACTIONS(77),
    [anon_sym_SLASH] = ACTIONS(77),
    [anon_sym_QMARK] = ACTIONS(77),
    [anon_sym_SQUOTE] = ACTIONS(77),
    [anon_sym_EQ] = ACTIONS(77),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [aux_sym_identifier_token1] = ACTIONS(79),
    [anon_sym_] = ACTIONS(85),
    [sym_bold_symbol_e] = ACTIONS(89),
  },
  [16] = {
    [sym_symbol] = STATE(19),
    [sym_identifier] = STATE(19),
    [sym_underlined_identifier] = STATE(13),
    [aux_sym_underlined_text_repeat1] = STATE(13),
    [anon_sym_POUND] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_DOLLAR] = ACTIONS(77),
    [anon_sym_TILDE] = ACTIONS(77),
    [anon_sym_COMMA] = ACTIONS(77),
    [anon_sym_DOT] = ACTIONS(77),
    [anon_sym_PERCENT] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(77),
    [anon_sym_SEMI] = ACTIONS(77),
    [anon_sym_BQUOTE] = ACTIONS(77),
    [anon_sym_BANG] = ACTIONS(77),
    [anon_sym_AT] = ACTIONS(77),
    [anon_sym_CARET] = ACTIONS(77),
    [anon_sym_AMP] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(77),
    [anon_sym_RBRACK] = ACTIONS(77),
    [anon_sym_BSLASH] = ACTIONS(77),
    [anon_sym_PIPE] = ACTIONS(77),
    [anon_sym_SLASH] = ACTIONS(77),
    [anon_sym_QMARK] = ACTIONS(77),
    [anon_sym_SQUOTE] = ACTIONS(77),
    [anon_sym_EQ] = ACTIONS(77),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [aux_sym_identifier_token1] = ACTIONS(79),
    [anon_sym_] = ACTIONS(81),
    [sym_underline_symbol] = ACTIONS(91),
  },
  [17] = {
    [anon_sym_POUND] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_DOLLAR] = ACTIONS(43),
    [anon_sym_TILDE] = ACTIONS(43),
    [anon_sym_COMMA] = ACTIONS(43),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_PERCENT] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(43),
    [anon_sym_BANG] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(43),
    [anon_sym_CARET] = ACTIONS(43),
    [anon_sym_AMP] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(43),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(43),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_BSLASH] = ACTIONS(43),
    [anon_sym_PIPE] = ACTIONS(43),
    [anon_sym_SLASH] = ACTIONS(43),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_EQ] = ACTIONS(43),
    [anon_sym_DQUOTE] = ACTIONS(43),
    [aux_sym_identifier_token1] = ACTIONS(43),
    [anon_sym_] = ACTIONS(43),
    [sym_bold_symbol_e] = ACTIONS(43),
    [sym_underline_symbol] = ACTIONS(43),
  },
  [18] = {
    [anon_sym_POUND] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(47),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_DOLLAR] = ACTIONS(47),
    [anon_sym_TILDE] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(47),
    [anon_sym_DOT] = ACTIONS(47),
    [anon_sym_PERCENT] = ACTIONS(47),
    [anon_sym_PLUS] = ACTIONS(47),
    [anon_sym_SEMI] = ACTIONS(47),
    [anon_sym_BQUOTE] = ACTIONS(47),
    [anon_sym_BANG] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(47),
    [anon_sym_CARET] = ACTIONS(47),
    [anon_sym_AMP] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(47),
    [anon_sym_RPAREN] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(47),
    [anon_sym_RBRACE] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(47),
    [anon_sym_RBRACK] = ACTIONS(47),
    [anon_sym_BSLASH] = ACTIONS(47),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_SLASH] = ACTIONS(47),
    [anon_sym_QMARK] = ACTIONS(47),
    [anon_sym_SQUOTE] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(47),
    [anon_sym_DQUOTE] = ACTIONS(47),
    [aux_sym_identifier_token1] = ACTIONS(47),
    [anon_sym_] = ACTIONS(47),
    [sym_bold_symbol_e] = ACTIONS(47),
    [sym_underline_symbol] = ACTIONS(47),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(93), 31,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_SEMI,
      anon_sym_BQUOTE,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_CARET,
      anon_sym_AMP,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BSLASH,
      anon_sym_PIPE,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_SQUOTE,
      anon_sym_EQ,
      anon_sym_DQUOTE,
      aux_sym_identifier_token1,
      anon_sym_,
      sym_underline_symbol,
  [34] = 1,
    ACTIONS(95), 31,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_SEMI,
      anon_sym_BQUOTE,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_CARET,
      anon_sym_AMP,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BSLASH,
      anon_sym_PIPE,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_SQUOTE,
      anon_sym_EQ,
      anon_sym_DQUOTE,
      aux_sym_identifier_token1,
      anon_sym_,
      sym_bold_symbol_e,
  [68] = 10,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 1,
      anon_sym_LF,
    ACTIONS(105), 1,
      anon_sym_TAB,
    ACTIONS(108), 1,
      anon_sym_TAB_TAB,
    ACTIONS(111), 1,
      anon_sym_TAB_TAB_TAB,
    STATE(39), 1,
      sym_title_starter,
    STATE(45), 1,
      sym_starter,
    STATE(21), 7,
      sym__definition,
      sym_title_definition,
      sym_header_definition,
      sym_subheader_definition,
      sym_section_definition,
      sym_normal_definition,
      aux_sym_source_file_repeat1,
    ACTIONS(99), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [113] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(33), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(116), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(114), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [156] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(38), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(126), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(124), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [199] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(35), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(130), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(128), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [242] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(23), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(134), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(132), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [285] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(36), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(138), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(136), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [328] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(38), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(134), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(132), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [371] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(38), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(116), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(114), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [414] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(37), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(142), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(140), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [457] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(32), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(146), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(144), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [500] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(27), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(150), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(148), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [543] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(38), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(154), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(152), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [586] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(38), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(158), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(156), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [629] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(38), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(142), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(140), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [672] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(38), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(146), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(144), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [715] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(38), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(150), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(148), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [758] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(38), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(162), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(160), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [801] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(168), 1,
      aux_sym_identifier_token1,
    ACTIONS(171), 1,
      sym_bold_symbol_s,
    ACTIONS(174), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(38), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(166), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(164), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [844] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(28), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(179), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(177), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [887] = 9,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(118), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      sym_bold_symbol_s,
    ACTIONS(122), 1,
      sym_underline_symbol,
    STATE(2), 1,
      sym_text,
    STATE(34), 1,
      aux_sym_title_definition_repeat1,
    ACTIONS(183), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    STATE(10), 4,
      sym_expression,
      sym_identifier,
      sym_bold_text,
      sym_underlined_text,
    ACTIONS(181), 12,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
  [930] = 10,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(9), 1,
      anon_sym_LF,
    ACTIONS(11), 1,
      anon_sym_TAB,
    ACTIONS(13), 1,
      anon_sym_TAB_TAB,
    ACTIONS(15), 1,
      anon_sym_TAB_TAB_TAB,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    STATE(39), 1,
      sym_title_starter,
    STATE(45), 1,
      sym_starter,
    STATE(21), 7,
      sym__definition,
      sym_title_definition,
      sym_header_definition,
      sym_subheader_definition,
      sym_section_definition,
      sym_normal_definition,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [975] = 3,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(189), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    ACTIONS(187), 15,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
      aux_sym_identifier_token1,
      sym_bold_symbol_s,
      sym_underline_symbol,
  [1000] = 3,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(193), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    ACTIONS(191), 15,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
      aux_sym_identifier_token1,
      sym_bold_symbol_s,
      sym_underline_symbol,
  [1025] = 3,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(197), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    ACTIONS(195), 15,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
      aux_sym_identifier_token1,
      sym_bold_symbol_s,
      sym_underline_symbol,
  [1050] = 3,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(201), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    ACTIONS(199), 15,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
      aux_sym_identifier_token1,
      sym_bold_symbol_s,
      sym_underline_symbol,
  [1075] = 3,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(205), 2,
      anon_sym_TAB,
      anon_sym_TAB_TAB,
    ACTIONS(203), 15,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LF,
      anon_sym_TAB_TAB_TAB,
      aux_sym_identifier_token1,
      sym_bold_symbol_s,
      sym_underline_symbol,
  [1100] = 8,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(209), 1,
      anon_sym_TAB,
    ACTIONS(211), 1,
      anon_sym_TAB_TAB,
    ACTIONS(213), 1,
      anon_sym_TAB_TAB_TAB,
    STATE(22), 1,
      sym_title_starter,
    STATE(45), 1,
      sym_starter,
    ACTIONS(207), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(7), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [1134] = 6,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(215), 1,
      anon_sym_TAB,
    STATE(31), 1,
      sym_section_starter,
    STATE(44), 1,
      sym_starter,
    STATE(49), 1,
      aux_sym_section_definition_repeat1,
    ACTIONS(7), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [1161] = 6,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(217), 1,
      anon_sym_TAB,
    STATE(25), 1,
      sym_section_starter,
    STATE(44), 1,
      sym_starter,
    STATE(54), 1,
      aux_sym_section_definition_repeat1,
    ACTIONS(7), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [1188] = 6,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(217), 1,
      anon_sym_TAB,
    STATE(31), 1,
      sym_section_starter,
    STATE(44), 1,
      sym_starter,
    STATE(54), 1,
      aux_sym_section_definition_repeat1,
    ACTIONS(7), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [1215] = 6,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(219), 1,
      anon_sym_TAB,
    STATE(26), 1,
      sym_section_starter,
    STATE(44), 1,
      sym_starter,
    STATE(50), 1,
      aux_sym_section_definition_repeat1,
    ACTIONS(7), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [1242] = 4,
    ACTIONS(3), 1,
      anon_sym_,
    STATE(30), 1,
      sym_subheader_starter,
    STATE(46), 1,
      sym_starter,
    ACTIONS(7), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [1263] = 4,
    ACTIONS(3), 1,
      anon_sym_,
    STATE(29), 1,
      sym_header_starter,
    STATE(42), 1,
      sym_starter,
    ACTIONS(7), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [1284] = 4,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(223), 1,
      anon_sym_TAB,
    STATE(54), 1,
      aux_sym_section_definition_repeat1,
    ACTIONS(221), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [1305] = 4,
    ACTIONS(3), 1,
      anon_sym_,
    STATE(24), 1,
      sym_subheader_starter,
    STATE(46), 1,
      sym_starter,
    ACTIONS(7), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [1326] = 4,
    ACTIONS(3), 1,
      anon_sym_,
    STATE(40), 1,
      sym_header_starter,
    STATE(42), 1,
      sym_starter,
    ACTIONS(7), 9,
      anon_sym_POUND,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_PLUS,
  [1347] = 2,
    ACTIONS(3), 1,
      anon_sym_,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(19)] = 0,
  [SMALL_STATE(20)] = 34,
  [SMALL_STATE(21)] = 68,
  [SMALL_STATE(22)] = 113,
  [SMALL_STATE(23)] = 156,
  [SMALL_STATE(24)] = 199,
  [SMALL_STATE(25)] = 242,
  [SMALL_STATE(26)] = 285,
  [SMALL_STATE(27)] = 328,
  [SMALL_STATE(28)] = 371,
  [SMALL_STATE(29)] = 414,
  [SMALL_STATE(30)] = 457,
  [SMALL_STATE(31)] = 500,
  [SMALL_STATE(32)] = 543,
  [SMALL_STATE(33)] = 586,
  [SMALL_STATE(34)] = 629,
  [SMALL_STATE(35)] = 672,
  [SMALL_STATE(36)] = 715,
  [SMALL_STATE(37)] = 758,
  [SMALL_STATE(38)] = 801,
  [SMALL_STATE(39)] = 844,
  [SMALL_STATE(40)] = 887,
  [SMALL_STATE(41)] = 930,
  [SMALL_STATE(42)] = 975,
  [SMALL_STATE(43)] = 1000,
  [SMALL_STATE(44)] = 1025,
  [SMALL_STATE(45)] = 1050,
  [SMALL_STATE(46)] = 1075,
  [SMALL_STATE(47)] = 1100,
  [SMALL_STATE(48)] = 1134,
  [SMALL_STATE(49)] = 1161,
  [SMALL_STATE(50)] = 1188,
  [SMALL_STATE(51)] = 1215,
  [SMALL_STATE(52)] = 1242,
  [SMALL_STATE(53)] = 1263,
  [SMALL_STATE(54)] = 1284,
  [SMALL_STATE(55)] = 1305,
  [SMALL_STATE(56)] = 1326,
  [SMALL_STATE(57)] = 1347,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_title_definition_repeat1, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_title_definition_repeat1, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_underlined_text, 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_underlined_text, 2),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_underlined_text, 3),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_underlined_text, 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold_text, 3),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold_text, 3),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold_text, 2),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold_text, 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_underlined_text_repeat1, 2), SHIFT_REPEAT(18),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_underlined_text_repeat1, 2), SHIFT_REPEAT(17),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_underlined_text_repeat1, 2), SHIFT_REPEAT(19),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_underlined_text_repeat1, 2),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_text_repeat1, 2), SHIFT_REPEAT(18),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_text_repeat1, 2), SHIFT_REPEAT(17),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_text_repeat1, 2), SHIFT_REPEAT(20),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bold_text_repeat1, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_underlined_identifier, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold_identifier, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(43),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(47),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(56),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(55),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_definition, 2),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title_definition, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 5),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_definition, 5),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subheader_definition, 2),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subheader_definition, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 4),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_definition, 4),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 2),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_definition, 2),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_definition, 3),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_definition, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subheader_definition, 3),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subheader_definition, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 3),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_definition, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subheader_definition, 4),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subheader_definition, 4),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_definition, 3),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title_definition, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_definition, 4),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_definition, 4),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_title_definition_repeat1, 2),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_title_definition_repeat1, 2),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_definition_repeat1, 2), SHIFT_REPEAT(8),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_definition_repeat1, 2), SHIFT_REPEAT(15),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_definition_repeat1, 2), SHIFT_REPEAT(16),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_definition, 1),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title_definition, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_definition, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_definition, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_starter, 1),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_starter, 1),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_starter, 1),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_starter, 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_starter, 1),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_starter, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_starter, 1),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title_starter, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subheader_starter, 1),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subheader_starter, 1),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_normal_definition, 1),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_definition_repeat1, 2),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_definition_repeat1, 2), SHIFT_REPEAT(54),
  [226] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_kojl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
